# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://diktam.com/"
defaultContentLanguage = "zh-Hans"
enableRobotsTXT = true

[pagination]
  pagerSize = 100 # posts页面的分页大小。注意，太大会导致页面加载变慢。进而（posts）页面的影响SEO

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
  
  # 参考：https://gohugo.io/methods/site/config/#services
  [services.googleAnalytics]
    id = 'G-WKMP5RJMN6'
