languageCode = "zh"
languageName = "简体中文"
languageDirection = "ltr"

title = "譚譚軟件開發" # 博客标题

[params]
  dateFormat = "2006年1月2日"
  # mainSections = ["section1", "section2"] # 显示在最新文章列表中的部分。如果未提供，则使用文章数最多的部分。

[params.author]
  name = "Dik Tam"
  image = "images/avatar.jpg"
  headline = "软件开发人员"
  bio = "只是喜欢写代码。" # 文章页脚中现实
  # links = [
    # { email = "mailto:diktamxx@gmail.com" }
  # ]
