# -- Theme Options --
# colorScheme = "Cherry"
colorScheme = "Diy"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = true
enableImageLazyLoading = true
enableImageWebp = true

description = "一个软件开发人员的个人博客。"
keywords = [
  "Java","Scala","Python","JavaScript","CSS","HTML",
  "React","Next.js","Webpack",
  "MySQL","PostgreSQL",
  "Object-oriented programming","OOP","Functional programming","FP",
  "Redis","Elasticsearch","Cassandra","Kafka","Neo4j","MongoDB",
  "Domain-driven design","DDD","Microservices",
  "Linux","Ubuntu",
  "Critical thinking","Independent thinking"
]

[header]
  showTitle = false

[footer]
  showThemeAttribution = false
  showAppearanceSwitcher = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 5

[article]
  # showDate = true
  # showDateUpdated = true
  showDate = false
  showDateUpdated = false

  showDraftLabel = true # 在使用 --buildDrafts 构建站点时，在文章旁边显示草稿标签
  showTableOfContents = false
  showHeadingAnchors = false
  showComments = true
  showPagination = false

  showReadingTime = false
  showTaxonomies = false # 显示标签必须开启showReadingTime

[taxonomy]
  showTermCount = true

[list]
  showSummary = true
