User: |md
  ## 用户

  浏览内容
| {
  shape: c4-person
}

BlogSystem: |md
  ## 博客系统
  [内部系统]

  提供专业内容
| {
  shape: rectangle
}

EmailSystem: |md
  ## 邮件系统
  [外部系统]

  提供通知服务
| {
  shape: rectangle
}

User -> BlogSystem: "订阅"
BlogSystem -> EmailSystem: "反馈"
EmailSystem -> User: "通知"



